<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permintaan_model extends CI_Model
{

    public $table = 'permintaan';
    public $id = 'permintaan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($param = '')
    {
        if (!empty($param)) {
            $this->db->where('tanggal_permintaan >=', $param['start']);
            $this->db->where('tanggal_permintaan <=', $param['end']);
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_limit()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db
            ->limit(5)
            ->get($this->table)->result();
    }

    function generatekodeReq()
    {

        $this->db->select('RIGHT(kode_permintaan,4) as kode_permintaan', false);
        $this->db->order_by("kode_permintaan", "DESC");
        $this->db->limit(1);
        $query = $this->db->get('permintaan');

        // CEK JIKA DATA ADA
        if ($query->num_rows() <> 0) {
            $data       = $query->row(); // ambil satu baris data
            $kodeReq  = intval($data->kode_permintaan) + 1; // tambah 1
        } else {
            $kodeReq  = 1; // isi dengan 1
        }

        $lastKode = str_pad($kodeReq, 4, "0", STR_PAD_LEFT);
        $tahun    = date("Y");
        $REQ      = "REQ";

        $newKode  = $REQ . "/" . $tahun . "/" . $lastKode;

        return $newKode;  // return kode baru

    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('permintaan_id', $q);
        $this->db->or_like('kode_permintaan', $q);
        $this->db->or_like('nama_karyawan', $q);
        $this->db->or_like('nip', $q);
        $this->db->or_like('jabatan', $q);
        $this->db->or_like('tanggal_permintaan', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Permintaan_model.php */
/* Location: ./application/models/Permintaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-06 03:58:34 */
/* http://harviacode.com */